database:
  default: sqlite
  connection:
    postgres:
      driver: postgres
      host: localhost
      port: 5432
      database: circuit
      username: postgres
      password: 111111
      schema: public
      sslmode: disable
    sqlite:
      driver: sqlite
      database: ./circuit.db
      schema: public